### PR TITLE
add new indentation marker option

### PR DESCRIPTION
**Pull request by ColeHoward**
# Why 
- This change introduces a new indentation marker option that can enhance code readability and align with personal coding styles.
- While this option can be applied across various languages, I think it works particularly well with languages that have indentation-sensitive syntax like Python or Yaml, making it a valuable addition for those working with them.
# What changed
- Added a new option in the `IndentationMarkerConfiguration` interface that allows users to choose between two types of indentation markers--`fullScope` and `codeOnly`. 
- Adjusted the indentation guides behavior to support both types, giving users the flexibility to choose according to their preference.
- Here's a before-and-after comparison that illustrates the new `codeOnly` behavior:

**Before** (`fullScope`):
Screenshot 2023-08-06 at 8 33 39 PM

**After** (`codeOnly`): 
Screenshot 2023-08-06 at 8 33 27 PM
- The `fullScope` behavior remains as the default, preserving existing functionality for those who prefer it.
# Test Plan
The new option can be applied like this:
```javascript
indentationMarkers({
  hideFirstIndent: false,
  highlightActiveBlock: true,
  markerType: "codeOnly", // The new option
}),
```
- **Toggle**: Verify that the new indentation guide option can be toggled between the two options.
- **Various Languages Support**: Open code files in different programming languages and ensure that indentation guides only extend down to code within the scope.
- **Edge Cases**: Ensure indentation guides are correct when indentations are mixed, nested, and/or inconsistent. Ensure default is displayed when invalid option is passed in.

### CODE REVIEW

**Comment by sergeichestakov** [comment]
awesome, thanks for the PR! 🙏 

do you mind just adding a note in the README [here](https://github.com/replit/codemirror-indentation-markers/blob/main/README.md#options) detailing this option so that we have some documentation around it?

**Comment by ColeHoward** [comment]
Just updated the README!

**Review by sergeichestakov — APPROVED** [review]
neat, thanks! 📝

**Comment by sergeichestakov** [comment]
published as part of `6.4.3`!

**Pull request merged**
